/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.CImages;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import LibTimer.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Alexander
 */
public class FrmMenuPrincipal extends javax.swing.JFrame implements Runnable{

    Thread hilo3;
    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        setMouse();
        
        hilo3=new Thread(this);
    }
    
    public void setMouse(){
        ImageIcon cur=new ImageIcon("Resources\\images\\martillo.png");
        Cursor c;
        Toolkit tk=Toolkit.getDefaultToolkit();
        
        c=tk.createCustomCursor(cur.getImage(), new Point(1,1), null);
        setCursor(c);
    }
    
    //Metodo para iniciar el juego
    
    public void play(){
        // TODO add your handling code here:
        CImages imgs=new CImages();
        imgs.create();
        
        FrmPlay objfrm=new FrmPlay();
        objfrm.show();
        

        //Para ubicar el PROGRESSBAR abajo del FRMPLAY
        Dimension height=objfrm.getSize();
        Point po=new Point();
        po=objfrm.getLocation();
        //this.dispose();
        
        //instancio el reloj de juego
        CTimer frame = new CTimer();
        frame.setUndecorated(true); //desactivar la barra superior del frame
        frame.setMinimumSize(new Dimension(850, 20));
        frame.relocation(frame,po.x+8,height.height+po.y-8);
        frame.display(frame);
        frame.iterate(20); //mando como parametro los segundos del juego
        //frame.end();
        
    }
    
    @Override
    public void run(){
        play();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHow = new javax.swing.JLabel();
        btnPlay = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHow.setFont(new java.awt.Font("Showcard Gothic", 0, 26)); // NOI18N
        btnHow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHow.setText("COMO");
        btnHow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHowMouseClicked(evt);
            }
        });
        jPanel1.add(btnHow, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 100, 50));

        btnPlay.setFont(new java.awt.Font("Showcard Gothic", 0, 26)); // NOI18N
        btnPlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPlay.setText("JUGAR");
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });
        jPanel1.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 100, 50));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/menuprincipal.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 660, 350));

        jPanel2.setBackground(new java.awt.Color(46, 204, 113));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 3, 68)); // NOI18N
        jLabel2.setText("TOPO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 330, 90));

        jPanel3.setBackground(new java.awt.Color(240, 52, 52));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 3, 68)); // NOI18N
        jLabel1.setText("ESPE");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 190, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        // TODO add your handling code here:
        
        hilo3.start();
    }//GEN-LAST:event_btnPlayMouseClicked

    private void btnHowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHowMouseClicked
        // TODO add your handling code here:
        FrmHowGame objfrm=new FrmHowGame();
        objfrm.show();
    }//GEN-LAST:event_btnHowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHow;
    private javax.swing.JLabel btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
