/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

//import Controller.*;

import Controller.*;
import java.awt.Image;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import LibScore.*;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
//import javafx.scene.Cursor;

/**
 *
 * @author Alexander
 */
public class FrmPlay extends javax.swing.JFrame implements Runnable{

    CRulesGame rules=new CRulesGame(this);
    CScore score=new CScore();
    //CScore score=new CScore();
    
    JLabel[] lbls=new JLabel[10];
    
    Thread hilo2;
    
    int timeSeconds=0;
    
    /**
     * Creates new form FrmPlay
     */
    public FrmPlay(){
        initComponents();
        this.setLocationRelativeTo(null);
        initializeLabels();
        setMouse();
        
        hilo2=new Thread(this);
        hilo2.start();
    }
    
    public void setMouse(){
        ImageIcon cur=new ImageIcon("Resources\\images\\martillo.png");
        Cursor c;
        Toolkit tk=Toolkit.getDefaultToolkit();
        
        c=tk.createCustomCursor(cur.getImage(), new Point(1,1), null);
        setCursor(c);
    }
    //inicializo los labels para las imgs
    public void initializeLabels(){
        lbls[0]=new JLabel();
        lbls[0]=lblHueco1;
        lbls[1]=new JLabel();
        lbls[1]=lblHueco2;
        lbls[2]=new JLabel();
        lbls[2]=lblHueco3;
        lbls[3]=new JLabel();
        lbls[3]=lblHueco4;
        lbls[4]=new JLabel();
        lbls[4]=lblHueco5;
        lbls[5]=new JLabel();
        lbls[5]=lblHueco6;
        lbls[6]=new JLabel();
        lbls[6]=lblHueco7;
        lbls[7]=new JLabel();
        lbls[7]=lblHueco8;
        lbls[8]=new JLabel();
        lbls[8]=lblHueco9;
        lbls[9]=new JLabel();
        lbls[9]=lblHueco10;

        //rules.setHole(lbls);
    }

@Override
    public void run(){
        while(timeSeconds<20){
            rules.setHole(lbls);
            try {
                lblScore.setText(String.valueOf(score.getScore()));
                Thread.sleep(1000);
                timeSeconds++;
            } catch (InterruptedException ex) {
                Logger.getLogger(FrmPlay.class.getName()).log(Level.SEVERE, null, ex);
            }
            //lblScore.setText(String.valueOf(score.getScore()));
        }
        JOptionPane.showMessageDialog(null, "SE TERMINO EL TIEMPO");
        sendScore();
        this.setEnabled(false);
    }
    
    //para enviar el puntaje al otro cliente
    public void sendScore(){
        int numscore,attempts,hits,fails;
        
        numscore=score.getScore();
        attempts=score.getAttempts();
        hits=score.getHits();
        fails=score.getFails();
        
        ViewClient obj=new ViewClient(numscore,attempts,hits,fails);
        obj.show();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHueco1 = new javax.swing.JLabel();
        lblHueco2 = new javax.swing.JLabel();
        lblHueco3 = new javax.swing.JLabel();
        lblHueco4 = new javax.swing.JLabel();
        lblHueco5 = new javax.swing.JLabel();
        lblHueco6 = new javax.swing.JLabel();
        lblHueco7 = new javax.swing.JLabel();
        lblHueco8 = new javax.swing.JLabel();
        lblHueco9 = new javax.swing.JLabel();
        lblHueco10 = new javax.swing.JLabel();
        lblLife1 = new javax.swing.JLabel();
        lblLife2 = new javax.swing.JLabel();
        lblLife3 = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHueco1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHueco1MouseClicked(evt);
            }
        });
        jPanel1.add(lblHueco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 80, 90));

        lblHueco2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHueco2MouseClicked(evt);
            }
        });
        jPanel1.add(lblHueco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 80, 90));

        lblHueco3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHueco3MouseClicked(evt);
            }
        });
        jPanel1.add(lblHueco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 80, 90));

        lblHueco4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHueco4MouseClicked(evt);
            }
        });
        jPanel1.add(lblHueco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 80, 90));

        lblHueco5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHueco5MouseClicked(evt);
            }
        });
        jPanel1.add(lblHueco5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 80, 90));

        lblHueco6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHueco6MouseClicked(evt);
            }
        });
        jPanel1.add(lblHueco6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 80, 90));

        lblHueco7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHueco7MouseClicked(evt);
            }
        });
        jPanel1.add(lblHueco7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 80, 90));

        lblHueco8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHueco8MouseClicked(evt);
            }
        });
        jPanel1.add(lblHueco8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 80, 90));

        lblHueco9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHueco9MouseClicked(evt);
            }
        });
        jPanel1.add(lblHueco9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 80, 90));

        lblHueco10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHueco10MouseClicked(evt);
            }
        });
        jPanel1.add(lblHueco10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 80, 90));

        lblLife1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/corazon.png"))); // NOI18N
        jPanel1.add(lblLife1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 30, 30));

        lblLife2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/corazon.png"))); // NOI18N
        jPanel1.add(lblLife2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 30, 30));

        lblLife3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/sincora.png"))); // NOI18N
        jPanel1.add(lblLife3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 30, 30));

        lblLevel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLevel.setText("00");
        jPanel1.add(lblLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 60, 30));

        lblScore.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScore.setText("00");
        jPanel1.add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 560, 140, 30));

        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fondo.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHueco1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHueco1MouseClicked
        // TODO add your handling code here:
        score.check(lblHueco1.getIcon().toString());
        System.out.println(lblHueco1.getIcon());
        rules.blankLbl(lblHueco1);
    }//GEN-LAST:event_lblHueco1MouseClicked

    private void lblHueco2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHueco2MouseClicked
        // TODO add your handling code here:
        score.check(lblHueco2.getIcon().toString());
        System.out.println(lblHueco2.getIcon());
        rules.blankLbl(lblHueco2);
    }//GEN-LAST:event_lblHueco2MouseClicked

    private void lblHueco3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHueco3MouseClicked
        // TODO add your handling code here:
        score.check(lblHueco3.getIcon().toString());
        System.out.println(lblHueco3.getIcon());
        rules.blankLbl(lblHueco3);
    }//GEN-LAST:event_lblHueco3MouseClicked

    private void lblHueco4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHueco4MouseClicked
        // TODO add your handling code here:
        score.check(lblHueco4.getIcon().toString());
        System.out.println(lblHueco4.getIcon());
        rules.blankLbl(lblHueco4);
    }//GEN-LAST:event_lblHueco4MouseClicked

    private void lblHueco5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHueco5MouseClicked
        // TODO add your handling code here:
        score.check(lblHueco5.getIcon().toString());
        System.out.println(lblHueco5.getIcon());
        rules.blankLbl(lblHueco5);
    }//GEN-LAST:event_lblHueco5MouseClicked

    private void lblHueco6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHueco6MouseClicked
        // TODO add your handling code here:
        score.check(lblHueco6.getIcon().toString());
        System.out.println(lblHueco6.getIcon());
        rules.blankLbl(lblHueco6);
    }//GEN-LAST:event_lblHueco6MouseClicked

    private void lblHueco7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHueco7MouseClicked
        // TODO add your handling code here:
        score.check(lblHueco7.getIcon().toString());
        System.out.println(lblHueco7.getIcon());
        rules.blankLbl(lblHueco7);
    }//GEN-LAST:event_lblHueco7MouseClicked

    private void lblHueco8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHueco8MouseClicked
        // TODO add your handling code here:
        score.check(lblHueco8.getIcon().toString());
        System.out.println(lblHueco8.getIcon());
        rules.blankLbl(lblHueco8);
    }//GEN-LAST:event_lblHueco8MouseClicked

    private void lblHueco9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHueco9MouseClicked
        // TODO add your handling code here:
        score.check(lblHueco9.getIcon().toString());
        System.out.println(lblHueco9.getIcon());
        rules.blankLbl(lblHueco9);
    }//GEN-LAST:event_lblHueco9MouseClicked

    private void lblHueco10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHueco10MouseClicked
        // TODO add your handling code here:
        score.check(lblHueco10.getIcon().toString());
        System.out.println(lblHueco10.getIcon());
        rules.blankLbl(lblHueco10);
    }//GEN-LAST:event_lblHueco10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHueco1;
    private javax.swing.JLabel lblHueco10;
    private javax.swing.JLabel lblHueco2;
    private javax.swing.JLabel lblHueco3;
    private javax.swing.JLabel lblHueco4;
    private javax.swing.JLabel lblHueco5;
    private javax.swing.JLabel lblHueco6;
    private javax.swing.JLabel lblHueco7;
    private javax.swing.JLabel lblHueco8;
    private javax.swing.JLabel lblHueco9;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblLife1;
    private javax.swing.JLabel lblLife2;
    private javax.swing.JLabel lblLife3;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables
}
