package View;


import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import LibScore.*;
import Model.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alexander
 */
public class ViewClient extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form ViewClient
     */
    public ViewClient(int score,int attempts,int hits,int fails) {
        initComponents();
        
        scoreEnd(score, attempts, hits, fails);
        
        Thread hilo=new Thread(this);
        hilo.start();
        
        
    }

    private ViewClient() {
        
    }
    
    public void scoreEnd(int score,int attempts,int hits,int fails){
        //txtIpCliente.setText(ip);
        txtScore.setText(String.valueOf(score));
        txtAttempts.setText(String.valueOf(attempts));
        txtHits.setText(String.valueOf(hits));
        txtFails.setText(String.valueOf(fails));
    }
    
    @Override
    public void run() {
        String ip;
        int score,attempts,hits,fails;
        try{
            ServerSocket server_cliente=new ServerSocket(9090);
            Socket cliente;
            
            CScore paquete_recibido;
            
            while(true){
                cliente=server_cliente.accept();
                
                ObjectInputStream flujo_entrada=new ObjectInputStream(cliente.getInputStream());
                paquete_recibido=(CScore) flujo_entrada.readObject();
                
                ip=paquete_recibido.getIp();
                score=paquete_recibido.getScore();
                attempts=paquete_recibido.getAttempts();
                hits=paquete_recibido.getHits();
                fails=paquete_recibido.getFails();
                
                txaCliente.append(" IP:"+ip+" Puntaje:"+score+" intentos:"+attempts+" aciertos:"+hits+" fallidos:"+fails);
                
            }
        }catch(Exception e){
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEnviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaCliente = new javax.swing.JTextArea();
        txtScore = new javax.swing.JTextField();
        txtIpCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFails = new javax.swing.JTextField();
        txtAttempts = new javax.swing.JTextField();
        txtHits = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnviar.setText("Guardar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 413, 100, 40));

        txaCliente.setColumns(20);
        txaCliente.setRows(5);
        jScrollPane1.setViewportView(txaCliente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 240, 190));
        jPanel1.add(txtScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 140, -1));
        jPanel1.add(txtIpCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, -1));

        jLabel3.setText("IP:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel4.setText("Puntaje");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2.setText("Intentos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel5.setText("Aciertos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel6.setText("Fallidos");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        jPanel1.add(txtFails, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 140, -1));
        jPanel1.add(txtAttempts, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 140, -1));
        jPanel1.add(txtHits, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        Conector c=new Conector();
        int score,attempts,hits,fails;
        score=Integer.parseInt(txtScore.getText());
        attempts=Integer.parseInt(txtAttempts.getText());
        hits=Integer.parseInt(txtHits.getText());
        fails=Integer.parseInt(txtFails.getText());
        
        c.start(txtIpCliente.getText(),score,attempts,hits,fails);
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaCliente;
    private javax.swing.JTextField txtAttempts;
    private javax.swing.JTextField txtFails;
    private javax.swing.JTextField txtHits;
    private javax.swing.JTextField txtIpCliente;
    private javax.swing.JTextField txtScore;
    // End of variables declaration//GEN-END:variables
}
